add_newline = false
format = "$directory$git_branch$git_status$nix_shell$character"

[directory]
truncation_length = 0

[nix_shell]
format = "via [$symbol$state( \\($name\\))]($style) "

[character]
success_symbol = "[INSERT](bold green)"
error_symbol = "[INSERT](bold red)"
vimcmd_symbol = "[NORMAL](bold yellow)"
