name: Lint / Python

on:
  push:
    branches: [main]
    paths:
      - "scripts/**/*.py"
      - .github/workflows/lint-python.yml
  pull_request:
    branches: [main]
    paths:
      - "scripts/**/*.py"
      - .github/workflows/lint-python.yml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-python:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Lint Python
        run: nix run --inputs-from ./nix-config nixpkgs#ruff -- check scripts
